{
  "modified": "2023-05-16T00:00:00Z",
  "published": "2020-06-18T00:00:00Z",
  "schema_version": "1.5.0",
  "id": "PSF-2020-3",
  "aliases": [
    "CVE-2020-14422"
  ],
  "summary": "[CVE-2020-14422] Hash collisions in IPv4Interface and IPv6Interface",
  "details": "Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in the IPv4Interface and IPv6Interface classes, which might allow a remote attacker to cause a denial of service if an application is affected by the performance of a dictionary containing IPv4Interface or IPv6Interface objects, and this attacker can cause many dictionary entries to be created. This is fixed in: v3.5.10, v3.5.10rc1; v3.6.12; v3.7.9; v3.8.4, v3.8.4rc1, v3.8.5, v3.8.6, v3.8.6rc1; v3.9.0, v3.9.0b4, v3.9.0b5, v3.9.0rc1, v3.9.0rc2.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "11d258ceafdf60ab3840f9a5700f2d0ad3e2e2d1"
            },
            {
              "fixed": "9a646aa82dfa62d70ca2a99ada901ee6cf9f82bd"
            },
            {
              "fixed": "b30ee26e366bf509b7538d79bfec6c6d38d53f28"
            },
            {
              "fixed": "b98e7790c77a4378ec4b1c71b84138cb930b69b7"
            },
            {
              "fixed": "cfc7ff8d05f7a949a88b8a8dd506fb5c1c30d3e9"
            },
            {
              "fixed": "dc8ce8ead182de46584cc1ed8a8c51d48240cbd5"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "database_specific": {
    "cwe_ids": []
  },
  "references": [
    {
      "type": "REPORT",
      "url": "https://bugs.python.org/issue41004"
    }
  ]
}