{
  "modified": "2024-09-07T02:44:36.613Z",
  "published": "2024-05-07T21:02:55.284Z",
  "schema_version": "1.5.0",
  "id": "PSF-2024-3",
  "aliases": [
    "CVE-2024-4030"
  ],
  "details": "On Windows a directory returned by tempfile.mkdtemp() would not always have permissions set to restrict reading and writing to the temporary directory by other users, instead usually inheriting the correct permissions from the default location. Alternate configurations or users without a profile directory may not have the intended permissions.\n\nIf you\u2019re not using Windows or haven\u2019t changed the temporary directory location then you aren\u2019t affected by this vulnerability. On other platforms the returned directory is consistently readable and writable only by the current user.\n\nThis issue was caused by Python not supporting Unix permissions on Windows. The fix adds support for Unix \u201c700\u201d for the mkdir function on Windows which is used by mkdtemp() to ensure the newly created directory has the proper permissions.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "81939dad77001556c527485d31a2d0f4a759033e"
            },
            {
              "fixed": "8ed546679524140d8282175411fd141fe7df070d"
            },
            {
              "fixed": "35c799d79177b962ddace2fa068101465570a29a"
            },
            {
              "fixed": "5130731c9e779b97d00a24f54cdce73ce9975dfd"
            },
            {
              "fixed": "66f8bb76a15e64a1bb7688b177ed29e26230fdee"
            },
            {
              "fixed": "6d0850c4c8188035643586ab4d8ec2468abd699e"
            },
            {
              "fixed": "91e3669e01245185569d09e9e6e11641282971ee"
            },
            {
              "fixed": "94591dca510c796c7d40e9b4167ea56f2fdf28ca"
            },
            {
              "fixed": "c8f868dc52f98011d0f9b459b6487920bfb0ac4d"
            },
            {
              "fixed": "d86b49411753bf2c83291e3a14ae43fefded2f84"
            },
            {
              "fixed": "e1dfa978b1ad210d551385ad8073ec6154f53763"
            },
            {
              "fixed": "eb29e2f5905da93333d1ce78bc98b151e763ff46"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/PRGS5OR3N3PNPT4BMV2VAGN5GMUI5636/"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/issues/118486"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/81939dad77001556c527485d31a2d0f4a759033e"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/8ed546679524140d8282175411fd141fe7df070d"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/35c799d79177b962ddace2fa068101465570a29a"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/5130731c9e779b97d00a24f54cdce73ce9975dfd"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/66f8bb76a15e64a1bb7688b177ed29e26230fdee"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/6d0850c4c8188035643586ab4d8ec2468abd699e"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/91e3669e01245185569d09e9e6e11641282971ee"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/94591dca510c796c7d40e9b4167ea56f2fdf28ca"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/c8f868dc52f98011d0f9b459b6487920bfb0ac4d"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/d86b49411753bf2c83291e3a14ae43fefded2f84"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/e1dfa978b1ad210d551385ad8073ec6154f53763"
    },
    {
      "type": "FIX",
      "url": "https://github.com/python/cpython/commit/eb29e2f5905da93333d1ce78bc98b151e763ff46"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20240705-0005/"
    }
  ],
  "database_specific": {
    "cwe_ids": []
  }
}