{
  "schema_version": "1.5.0",
  "id": "CVE-2019-9948",
  "modified": "2020-08-22T16:06:15",
  "published": "2019-03-23T17:07:08",
  "summary": "urllib module local_file:// scheme",
  "details": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
  "affected": [
    {
      "ranges": [
        {
          "type": "GIT",
          "events": [
            {
              "fixed": "0c2b6a3943aa7b022e8eb4bfd9bffcddebf9a587"
            },
            {
              "fixed": "34bab215596671d0dec2066ae7d7450cd73f638b"
            },
            {
              "fixed": "4f06dae5d8d4400ba38d8502da620f07d4a5696e"
            },
            {
              "fixed": "4fe82a8eef7aed60de05bfca0f2c322730ea921e"
            },
            {
              "fixed": "b15bde8058e821b383d81fcae68b335a752083ca"
            }
          ],
          "repo": "https://github.com/python/cpython"
        }
      ]
    }
  ],
  "references": [],
  "database_specific": {
    "cwe_ids": []
  }
}